name: Scheduled genjson.py runner

on:
  schedule:
    - cron: '0 9 * * *'  # runs every day at 6 PM KST
  workflow_dispatch:      # optional manual run button

jobs:
  run-genjson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run genjson.py
        run: python genjson.py
