name: Scheduled genjson.py runner

on:
  schedule:
    - cron: '0 9 * * *'  # 6 PM KST (09:00 UTC)
  workflow_dispatch:

jobs:
  run-genjson:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run genjson.py
        run: python genjson.py
        
      - name: Copy posts.json to _site
        run: cp posts.json _site/posts.json